### ISSUE TITLE
AttributeError: module 'homeassistant.util.dt' has no attribute 'fromtimestamp'.

### ISSUE THREAD

**Issue by TurtleFX** [algirdasc/hass-eso#16]
Hello,
Thanks for your work.

I'm trying to configure your ESO integration but I'm receiving the following error: 
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eso/__init__.py:223
integration: ESO Energy Consumption (documentation, issues)
First occurred: 22:09:51 (1 occurrences)
Last logged: 22:09:51

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/eso/__init__.py", line 108, in async_first_start
    await async_import_generation(datetime.now())
  File "/config/custom_components/eso/__init__.py", line 101, in async_import_generation
    await async_insert_cost_statistics(
  File "/config/custom_components/eso/__init__.py", line 223, in async_insert_cost_statistics
    start_time = dt_util.fromtimestamp(min(cons_dataset.keys())).replace(tzinfo=dt_util.get_time_zone("Europe/Vilnius"))
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.dt' has no attribute 'fromtimestamp'. Did you mean: 'as_timestamp'?
```

Do you have any ideas on how to fix it? Do I need to install any dependencies?
My version of the Home Assistant:
Home Assistant OS 13.1
Home Assistant Core:      2024.9.2

**Comment by algirdasc** [comment]
Should be fixed in the newest version. Please update.

**Comment by TurtleFX** [comment]
Updated to the newest version.
Error seems to be gone. Thanks!
