### ISSUE TITLE
Neateina duomenys

### ISSUE THREAD

**Issue by PsYcHLT** [algirdasc/hass-eso#17]
Sveiki,

Neateina niekaip duomenys iš ESO, palikau HA šiek tiek paveikti, nuėjau į logus ir radau tokį error. Naudoju naujausią versiją. Auth turėtų veikti, kadangi opakeitus pass į blogą išmetama kitokia klaida.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eso/eso_client.py:35
integration: ESO Energy Consumption (documentation, issues)
First occurred: 2:42:51 PM (1 occurrences)
Last logged: 2:42:51 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/eso/__init__.py", line 87, in async_import_generation
    await hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 35, in login
    response = self.session.post(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by algirdasc** [comment]
Iš klaidos, panašu, kad ryšio problemos.

**Comment by PsYcHLT** [comment]
Na jau savaitė praėjo, duomenų vis dar 0...

**Comment by algirdasc** [comment]
Reikėtų daugiau konteksto:
1. Kaip HA paleistas? Dockeryje? HASSOS?
2. Ar iš to kompiuterio, kuriame sukasi HA, gali paieskti mano.eso.lt? Ką rašto paleidus komandą `curl -v https://mano.eso.lt`?
3. Ar neveikė nuo pat pradžių ar po kažkurio atnaujinimo?

**Comment by PsYcHLT** [comment]
1. Paleistas kaip proxmox VM based on debian
2. `➜  ~ curl -v https://mano.eso.lt
* Host mano.eso.lt:443 was resolved.
* IPv6: 2606:4700:20::681a:5e2, 2606:4700:20::ac43:49e2, 2606:4700:20::681a:4e2
* IPv4: 104.26.4.226, 104.26.5.226, 172.67.73.226
*   Trying 104.26.4.226:443...
* Connected to mano.eso.lt (104.26.4.226) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=eso.lt
*  start date: Sep  4 03:25:54 2024 GMT
*  expire date: Dec  3 03:25:53 2024 GMT
*  subjectAltName: host "mano.eso.lt" matched cert's "*.eso.lt"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://mano.eso.lt/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: mano.eso.lt]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.9.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: mano.eso.lt
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 200 
< date: Mon, 30 Sep 2024 18:02:44 GMT
< content-type: text/html; charset=UTF-8
< x-content-type-options: nosniff
< x-content-type-options: nosniff
< cache-control: must-revalidate, no-cache, private
< x-drupal-dynamic-cache: UNCACHEABLE
< content-language: lt
< x-frame-options: SAMEORIGIN
< expires: Sun, 19 Nov 1978 05:00:00 GMT
< content-security-policy: report-uri /report-csp-violation
< x-xss-protection: 1; mode=block
< strict-transport-security: max-age=15552000
< referrer-policy: strict-origin
< x-drupal-cache: HIT
< vary: Accept-Encoding
< set-cookie: eso_cookie=rd9o00000000000000000000ffff0a0a648co80; path=/; Httponly; Secure
< set-cookie: TS0182e471=014ec392150dbb9a668d55161c54a4635cfc2130de667f295f8b39ce28eab8eea3c44cdc1fe6887848e8c8c78ed11bfdc217b23b04; Path=/; Domain=.mano.eso.lt
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=s9NxOfmIXClkYMYpik4iM91fqshcKx0mNy%2FK3nA5LHTGvmYxFcI%2B7R0oJQYE2s7rqnasbmREr%2F4yAks%2FGMbRhu9lnLV5A71kO0x9oNiPAGVjSV45PgxDJNAhUB2N"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 8cb6202d1ab2cc2f-VNO
< 
<!DOCTYPE html>
<html lang="lt" dir="ltr">
  <head>
    <meta charset="utf-8" />
<script type="text/javascript" id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="3e5bf897-5c6d-4ea2-bfb0-33ef75b5b2da" async="async"></script>
<script src="/sites/default/files/hotjar/hotjar.script.js?sjz35z" data-cookieconsent="statistics" type="text/plain"></script>
<meta name="baggage" content="sentry-trace_id=bb803c64ae9f4d2eb294518e5d4d7e26,sentry-public_key=b6f50eb1c536419292ed95b22ac2ff92,sentry-environment=prod" />
<meta name="sentry-trace" content="bb803c64ae9f4d2eb294518e5d4d7e26-e24855af68d14e0d" />
<meta name="traceparent" content="00-bb803c64ae9f4d2eb294518e5d4d7e26-e24855af68d14e0d-00" />
<meta name="MobileOptimized" content="width" />
<meta name="HandheldFriendly" content="true" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<link rel="icon" href="/themes/esos/favicon.ico" type="image/vnd.microsoft.icon" />

    <title>Prisijungti | ESO savitarna</title>
    <meta name="format-detection" content="telephone=no">
    <meta property="og:image" content="https://mano.eso.lt/themes/esos/images/logo.png"/>
    <meta property="og:image:width" content="320" />
    <meta property="og:image:height" content="249" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i&display=swap&subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" media="all" href="/sites/default/files/css/css_vMMEgE7SfsFto9vTMAxCbvidLahqqJITlr4sRMIXLfE.css?delta=0&amp;language=lt&amp;theme=esos&amp;include=eJxtTlsOwjAMu1BZj1RlrcnK2mZawspuD4IJiceP5ZdkQyXEicz3nBjmVtrQ_BOdSsxUQkXKFEpus_pfa7AJFU53NVQ_ksJBRT0XGamc1PZHjR2LcEEwYs9WPyXxtx7oQjcXReaMUcy_2b9PZ2lG_TFaMUSpizQ0e51YSLXLmsKW0YPGNS9HUoQZSa52uHcpEWeO" />
<link rel="stylesheet" media="all" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link rel="stylesheet" media="all" href="/sites/default/files/css/css_et6BFRwEbg-vcKbDnO_wustGzn441yc2LNt_rmEFrqE.css?delta=2&amp;language=lt&amp;theme=esos&amp;include=eJxtTlsOwjAMu1BZj1RlrcnK2mZawspuD4IJiceP5ZdkQyXEicz3nBjmVtrQ_BOdSsxUQkXKFEpus_pfa7AJFU53NVQ_ksJBRT0XGamc1PZHjR2LcEEwYs9WPyXxtx7oQjcXReaMUcy_2b9PZ2lG_TFaMUSpizQ0e51YSLXLmsKW0YPGNS9HUoQZSa52uHcpEWeO" />
<link rel="stylesheet" media="all" href="/sites/default/files/css/css_JbpxToCmZzCXne3HYFgpDzpbbtRq83OkQP9mOc4IMig.css?delta=3&amp;language=lt&amp;theme=esos&amp;include=eJxtTlsOwjAMu1BZj1RlrcnK2mZawspuD4IJiceP5ZdkQyXEicz3nBjmVtrQ_BOdSsxUQkXKFEpus_pfa7AJFU53NVQ_ksJBRT0XGamc1PZHjR2LcEEwYs9WPyXxtx7oQjcXReaMUcy_2b9PZ2lG_TFaMUSpizQ0e51YSLXLmsKW0YPGNS9HUoQZSa52uHcpEWeO" />

    
  </head>
  <body>
            <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NBVSM5Z"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

    <a href="#main-content" class="visually-hidden focusable">
      Pereiti į pagrindinį turinį
    </a>
      <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas>
    <div class="layout-container--logged-out">
  <header role="banner">
  <div class="logged-in-header-wrapper">
    <div class="logo-cl">
      <a href="/" title="Pirmas" rel="home">
        <img src="/themes/esos/images/logo.svg" alt="Pirmas" />
      </a>
    </div>
    <div class="text-cl">
      <div class="text-wrapper">
        Energijos skirstymo operatoriaus savitarna
      </div>
    </div>
  </div>
</header>
  <div>
    <div data-drupal-messages-fallback class="hidden"></div>

  </div>

  
  <main role="main">
    <a id="main-content" tabindex="-1"></a>    <div class="layout-content">
      <div class="container wrapped-container loggedout-page-wrapper">
          <div>
    <div id="block-esos-page-title">
  
    
      
  <div class="page-block-title">
    <h1>Prisijungti</h1>
  </div>


  </div>
<div class="block-content-box class-system_main_block">
  <div id="block-esos-pagrindiniopuslapioturinys">
    
        
            <form class="user-login-form" data-drupal-selector="user-login-form" novalidate="novalidate" autocomplete="off" action="/" method="post" id="user-login-form" accept-charset="UTF-8">
  <div class="login-form-toggler">
    <div class="login-option">
      <label class="login-radio">
        <input type="radio" name="login_type" value="1" />
        <span class="radio-text">Namams</span>
      </label>
    </div>
    <div class="login-option">
      <label class="login-radio">
        <input type="radio" name="login_type" value="2" />
        <span class="radio-text">Verslui</span>
      </label>
    </div>
  </div>
  <div class="login-form-bg">
    <h2 class="login-form-title">Prisijunkite prie savitarnos</h2>
    <div class="js-form-item form-item js-form-type-email form-item-name js-form-item-name">
  <div class="form-element-layout">
        <div class="form-element-left">
                <label for="edit-name" class="js-form-required form-required">El. paštas</label>
                </div>
        <div class="form-element-right">
            <div class="input-type type-email">
        <input autocorrect="none" autocapitalize="none" spellcheck="false" autofocus="autofocus" autocomplete="username" data-drupal-selector="edit-name" aria-describedby="edit-name--description" type="email" id="edit-name" name="name" value="" size="60" maxlength="254" class="form-email required" required="required" aria-required="true" />

      </div>
                                <div id="edit-name--description" class="description">
          Įveskite el.pašto adresą
        </div>
          </div>
  </div>
</div>
<div class="js-form-item form-item js-form-type-password form-item-pass js-form-item-pass">
  <div class="form-element-layout">
        <div class="form-element-left">
                <label for="edit-pass" class="js-form-required form-required">Slaptažodis</label>
                </div>
        <div class="form-element-right">
            <div class="input-type type-password">
        
<div class="input-password-wrapper">
  <input autocomplete="off" data-drupal-selector="edit-pass" aria-describedby="edit-pass--description" type="password" id="edit-pass" name="pass" size="60" maxlength="128" class="form-text required" required="required" aria-required="true" />
  <span class="password-view-toggle"><i class="icon-eye-closed"></i></span>
</div>

      </div>
                                <div id="edit-pass--description" class="description">
          Įveskite slaptažodį
        </div>
          </div>
  </div>
</div>
<input autocomplete="off" data-drupal-selector="form-3szgtxnaj46dlk4puunfoutdei92tps7adt-8ww0xg8" type="hidden" name="form_build_id" value="form-3szGtXNaJ46DlK4puUNfoutDEI92TPs7ADT-8ww0xg8" />
<input data-drupal-selector="edit-user-login-form" type="hidden" name="form_id" value="user_login_form" />
<a href="https://www.eso.lt/web/duk/prisijungimo-klausimai-180" target="_blank" class="faq-link-private" data-drupal-selector="edit-login-faq-link-private" id="edit-login-faq-link-private">Negaliu prisijungti</a><a href="https://www.eso.lt/web/duk/prisijungimo-klausimai-180" target="_blank" class="faq-link-business" data-drupal-selector="edit-login-faq-link-business" id="edit-login-faq-link-business">Negaliu prisijungti</a><div data-drupal-selector="edit-actions" class="form-actions js-form-wrapper form-wrapper" id="edit-actions"><input data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="Prisijungti" class="button js-form-submit form-submit" />
</div>


            <a class="forgot-password-link" href="/user/password ">Pamiršau slaptažodį</a>
  </div>
</form>

      </div>
</div>
<div class="block-esos-auth-block">
  <div class="eso-auth-explain">
    Arba prisijunkite per:
  </div>
  <div id="block-esos-esoauthblock">
    
        
          <form class="eso-auth-block-form" data-drupal-selector="eso-auth-block-form" novalidate="novalidate" action="/" method="post" id="eso-auth-block-form" accept-charset="UTF-8">
  <input autocomplete="off" data-drupal-selector="form-x2-prhlpiihfpw3et1bx-eha5rtpekhpsrlgsie0ncs" type="hidden" name="form_build_id" value="form-x2-pRHlpIIhfPW3Et1BX_EhA5rTpeKHPSRLgsIe0ncs" />
<input data-drupal-selector="edit-eso-auth-block-form" type="hidden" name="form_id" value="eso_auth_block_form" />
<div class="auth-buttons-wrapper form-actions js-form-wrapper form-wrapper" data-drupal-selector="edit-actions" id="edit-actions--2"><input data-drupal-selector="edit-smartid" type="submit" id="edit-smartid" name="smartid" value="Smart ID" class="button js-form-submit form-submit" />
<input data-drupal-selector="edit-mobile" type="submit" id="edit-mobile" name="mobile" value="M-PARAŠAS" class="button js-form-submit form-submit" />
<input data-drupal-selector="edit-swedbank" type="submit" id="edit-swedbank" name="swedbank" value="Swedbank" class="button js-form-submit form-submit" />
<input data-drupal-selector="edit-luminor" type="submit" id="edit-luminor" name="luminor" value="Luminor" class="button js-form-submit form-submit" />
<input data-drupal-selector="edit-seb" type="submit" id="edit-seb" name="seb" value="SEB" class="button js-form-submit form-submit" />
<input data-drupal-selector="edit-sb" type="submit" id="edit-sb" name="sb" value="SB" class="button js-form-submit form-submit" />
</div>

</form>

      </div>
</div>


  </div>

                <div class="register-block">
          Dar neturite paskyros?
                                          <a class="btn btn-secondary" data-business-link="/user/register-initial-business-data" data-private-link="/user/register" href="/user/register">Registruotis</a>
        </div>
              </div>
    </div>  </main>
  <footer role="contentinfo">
      <div class="footer-second">
      <div class="footer-wrapper">
        <div class="footer-second-layout">
          <div class="footer-second-left">
              <div>
    <nav role="navigation" aria-labelledby="block-bottom-menu" id="block-bottom">
            
  <h2 class="visually-hidden" id="block-bottom-menu">Bottom</h2>
  

        
              <ul>
              <li>
        <a href="https://www.eso.lt/lt/privatumas.html" target="_blank">Privatumas</a>
              </li>
          <li>
        <a href="/ab-energijos-skirstymo-operatorius-savitarnos-svetaines-naudojimosi-taisykles" target="_blank" data-drupal-link-system-path="node/4">Taisyklės</a>
              </li>
        </ul>
  


  </nav>
<div id="block-socialmedialinks" class="block-social-media-links">
  
    
      

<ul class="social-media-links--platforms platforms inline horizontal">
      <li>
      <a class="social-media-link-icon--facebook" href="https://www.facebook.com/ESO-Energijos-skirstymo-operatorius-897851537029010/"  target="_blank" >
        <span class='fab fa-facebook fa-2x'></span>
      </a>

          </li>
      <li>
      <a class="social-media-link-icon--linkedin" href="https://www.linkedin.com/company/ab-%E2%80%9Eenergijos-skirstymo-operatorius%E2%80%9C-eso-"  target="_blank" >
        <span class='fab fa-linkedin fa-2x'></span>
      </a>

          </li>
      <li>
      <a class="social-media-link-icon--youtube_channel" href="https://www.youtube.com/channel/UCIPcGuBGHRPPpPSkTmLejXQ"  target="_blank" >
        <span class='fab fa-youtube fa-2x'></span>
      </a>

          </li>
  </ul>

  </div>

  </div>

          </div>
        </div>
      </div>
    </div>
  </footer>
</div>

  </div>

    
    <script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/","pathPrefix":"","currentPath":"user\/login","currentPathIsAdmin":false,"isFront":true,"currentLanguage":"lt","themePath":"themes\/esos"},"pluralDelimiter":"\u0003","suppressDeprecationErrors":true,"ajaxPageState":{"libraries":"eJxtjl0OwyAMgy_EypFQClmaFQhqsrLeflW3PuznxbK_WHKiyMw4ivl4OocqIU5gvnMiPLJ6yjJCvqhtmSu9WBYiTHK3oHHh9m42UO2ypLAy9vNCIpQxGJCnXb7zADd4fMLiFlix-kOdSmTIoWBiCPsHs_qrVIO-TxYcopQmFav9K_6iwSYs6HRTw-JHUHwCnKxnjg","theme":"esos","theme_token":null},"ajaxTrustedUrl":{"form_action_p_pvdeGsVG5zNF_XLGPTvYSKCf43t8qZYSwcfZl2uzM":true},"jquery":{"ui":{"datepicker":{"isRTL":false,"firstDay":0,"langCode":"lt"}}},"gtm":{"tagId":null,"settings":{"data_layer":"dataLayer","include_environment":false},"tagIds":["GTM-NBVSM5Z"]},"gtag":{"tagId":"","consentMode":false,"otherIds":[],"events":[],"additionalConfigInfo":[]},"eso_chat":{"api_key":"eso2568frtReWeb","auto_show_interval":300000},"raven":{"options":{"dsn":"https:\/\/b6f50eb1c536419292ed95b22ac2ff92@sentry.ignitis.lt\/3","environment":"prod","integrations":[],"autoSessionTracking":false,"sendClientReports":false},"showReportDialog":false,"browserTracingOptions":{"enableInp":false}},"cookiebot":{"message_placeholder_cookieconsent_optout_marketing_show":false,"message_placeholder_cookieconsent_optout_marketing":"\u003Cdiv class=\u0022cookiebot cookieconsent-optout-marketing\u0022\u003E\n\t\u003Cdiv class=\u0022cookieconsent-optout-marketing__inner\u0022\u003E\n\t\t\u003Cp\u003EPlease \u003Ca class=\u0022cookieconsent-optout-marketing__cookiebot-renew\u0022 href=\u0022!cookiebot_renew\u0022\u003Eaccept marketing-cookies\u003C\/a\u003E to view this embedded content from \u003Ca class=\u0022cookieconsent-optout-marketing__from-src-url\u0022 href=\u0022!cookiebot_from_src_url\u0022 target=\u0022_blank\u0022\u003E!cookiebot_from_src_url\u003C\/a\u003E\u003C\/p\u003E\n\n\t\u003C\/div\u003E\n\u003C\/div\u003E\n"},"user":{"uid":0,"permissionsHash":"0b711d2ef612f9108485c0ff1a4d41644550409ec0540738d0d1fc8f7704bdaf"}}</script>
<script src="/sites/default/files/js/js_BluYsMkX5wCJNkShantneMoK1eJ6jcENWixyLMwTtVk.js?scope=footer&amp;delta=0&amp;language=lt&amp;theme=esos&amp;include=eJxtTlsOwjAMu1BZj1RlrcnK2mZawspuD4IJiceP5ZdkQyXEicz3nBjmVtrQ_BOdSsxUQkXKFEpus_pfa7AJFU53NVQ_ksJBRT0XGamc1PZHjR2LcEEwYs9WPyXxtx7oQjcXReaMUcy_2b9PZ2lG_TFaMUSpizQ0e51YSLXLmsKW0YPGNS9HUoQZSa52uHcpEWeO"></script>
<script src="https://chat.eso.lt/embed/js/loadjs.min.js"></script>
<script src="https://chat.eso.lt/embed/js/loader.js"></script>
<script src="/sites/default/files/js/js_7cb24sKatZZ9H-ZXcFBwNH2kzrvU7k-ij4j6YD2iyBk.js?scope=footer&amp;delta=3&amp;language=lt&amp;theme=esos&amp;include=eJxtTlsOwjAMu1BZj1RlrcnK2mZawspuD4IJiceP5ZdkQyXEicz3nBjmVtrQ_BOdSsxUQkXKFEpus_pfa7AJFU53NVQ_ksJBRT0XGamc1PZHjR2LcEEwYs9WPyXxtx7oQjcXReaMUcy_2b9PZ2lG_TFaMUSpizQ0e51YSLXLmsKW0YPGNS9HUoQZSa52uHcpEWeO"></script>
<script src="/modules/contrib/google_tag/js/gtm.js?sjz35z"></script>
<script src="/modules/contrib/google_tag/js/gtag.js?sjz35z"></script>
<script src="/sites/default/files/js/js_NPcJtJJUBIFrtvKq3aAXXh9hqru5pcVsYJWITnf8ceg.js?scope=footer&amp;delta=6&amp;language=lt&amp;theme=esos&amp;include=eJxtTlsOwjAMu1BZj1RlrcnK2mZawspuD4IJiceP5ZdkQyXEicz3nBjmVtrQ_BOdSsxUQkXKFEpus_pfa7AJFU53NVQ_ksJBRT0XGamc1PZHjR2LcEEwYs9WPyXxtx7oQjcXReaMUcy_2b9PZ2lG_TFaMUSpizQ0e51YSLXLmsKW0YPGNS9HUoQZSa52uHcpEWeO"></script>

      </body>
</html>
* Connection #0 to host mano.eso.lt left intact
➜  ~ 
`

3. Neveikia nuo pat pradžių.

**Comment by PsYcHLT** [comment]
Gal turite idėjų kas gali būti?

**Comment by algirdasc** [comment]
Labas, neisivaizduoju. Iš klaidos pranešimo galima suprasti, kad kažkodėl pats ESO atjungia susijungimą, tačiau `curl` komanda praeina sėkmingai. Galbūt turi routerį ar kokį firewall isidiegęs, kuris galėtų atjunginėti connection'ą pagal User-Agent headerį ar kažką panašaus?

**Comment by matkvaid** [comment]
Sveiki,
as taip pat klaida gaunu. pastas, slaptazodis ir id teisingi, bandziau juos ir i kabutes suvesti - ka cia ne taip darau?

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eso/eso_client.py:59
integration: ESO Energy Consumption (documentation, issues)
First occurred: 8 November 2024 at 21:29:11 (4 occurrences)
Last logged: 09:29:11

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/eso/__init__.py", line 91, in async_import_generation
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 105, in fetch_dataset
    data = self.fetch(obj, date)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 59, in fetch
    raise Exception("Form ID not found. Check your credentials OR login to ESO and confirm contact information.")
Exception: Form ID not found. Check your credentials OR login to ESO and confirm contact information.

**Comment by juodikis** [comment]
Man taip pat jau kuris laikas nebeateina duomenys (jei tiksliau, nuo 2024-11-02)

Man rodos ESO į login formą įdėjo Cloudflare'o captcha ir būtent jis gadina reikalus. Nes anksčiau jungiantis jo nebuvo.

**Comment by algirdasc** [comment]
Bent man dabar bandant prisijungti - jokios CAPTCHA nereikalauja. Bet jei įdėjo CAPTCHA, tai liūdnesni reikalai tuomet.

**Comment by Grabauskas** [comment]
Pastebėjau, jog ir man buvo pradėję neateiti duomenys. Prisijungus tereikėjo atnaujinti kontaktinius duomenis ir po to vėl viskas suvažiavo į HA.

Kažkaip neatkreipiau dėmesio, kas įvyksta tuo metu. Bet spėčiau jog po prisijungimo ESO redirect'ina į kontaktinių duomenų atnaujinimo puslapį, o script'as to nesuhandlina.

Galbūt redirectina tik pirmą request'ą ir užtektu retry padaryti?

**Comment by matkvaid** [comment]
O klaida tokia pat? atnaujinau duomenis, nors ir neprasydavo nieko, captcha taip pat nemeta, bet vis system log'e buna si klaida: "Form ID not found. Check your credentials OR login to ESO and confirm contact information."

**Comment by Grabauskas** [comment]
Taip, tokia pati klaida. Šią naktį vėl tūrėjau tokį error'ą log'uose paryčiais, bet visgi kažkuriuo metu pavyko persiųsti duomenis. O dabar išvis, nuėjus į svetainę gaunu tokį:
![image](https://github.com/user-attachments/assets/35060a95-d967-41d4-9588-6488a86fd9d5)

**Comment by juodikis** [comment]
> Pastebėjau, jog ir man buvo pradėję neateiti duomenys. Prisijungus tereikėjo atnaujinti kontaktinius duomenis ir po to vėl viskas suvažiavo į HA.
> 
> Kažkaip neatkreipiau dėmesio, kas įvyksta tuo metu. Bet spėčiau jog po prisijungimo ESO redirect'ina į kontaktinių duomenų atnaujinimo puslapį, o script'as to nesuhandlina.
> 
> Galbūt redirectina tik pirmą request'ą ir užtektu retry padaryti?

Valio! Atnaujinus kontaktinius duomenis vėl viskas važiuoja! (šiaip keista logika, kodėl turėtų nevažiuot, bet whatever....)

O dėl paskutinio (cloudflare klaidos) tai panašu, kad vis dėlto yra cloudflare'o firewall'ai/captcha'os. Tai čia pats mano.eso.lt nulūžo ir dėl to nieko nepadarysi 🤷‍♂️

**Comment by matkvaid** [comment]
Nesuprantu ką aš tuomet blogai pasidariau - kontaktinius duomenis atnaujinau, nors ir neprašė. Eso puslapis atsidaro, kaip ir viskas veikia, bet vis dar gaunu tą pačią Form ID klaidą. 
konfiguracijoje kažkas ne taip? 
eso:
  username: mano@pastas.com
  password: slaptazodis
  objects:
    - name: Home
      id: 123456

**Comment by juodikis** [comment]
> Nesuprantu ką aš tuomet blogai pasidariau - kontaktinius duomenis atnaujinau, nors ir neprašė. Eso puslapis atsidaro, kaip ir viskas veikia, bet vis dar gaunu tą pačią Form ID klaidą. konfiguracijoje kažkas ne taip? eso: username: [mano@pastas.com](mailto:mano@pastas.com) password: slaptazodis objects: - name: Home id: 123456

Dėl visa ko pabandyk įtraukt "consumed" parametrą:

`eso:
  username: !secret eso_email
  password: !secret eso_password
  objects:
    - name: Home
      id: xxxxxxx
      consumed: true`

**Comment by PsYcHLT** [comment]
Sveiki, visgi perdiegimas padėjo ir viskas veikia. Tai kaip ir nelabai suprantu kodėl neveikė ir kodėl pradėjo veikti.
