### ISSUE TITLE
Exception: Form ID not found. Check your credentials.

### ISSUE THREAD

**Issue by gramasx** [algirdasc/hass-eso#6]
Labas,
doesn't work for me - getting this in HA system logs:

Logger: homeassistant
Source: custom_components/eso/eso_client.py:58
integration: ESO Energy Consumption ([documentation](https://github.com/algirdasc/hass-eso), [issues](https://github.com/algirdasc/hass-eso/issues))
First occurred: 21:05:48 (1 occurrences)
Last logged: 21:05:48
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/eso/__init__.py", line 102, in async_first_start
    await async_import_generation(datetime.now())
  File "/config/custom_components/eso/__init__.py", line 86, in async_import_generation
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 104, in fetch_dataset
    data = self.fetch(obj, date)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 58, in fetch
    raise Exception("Form ID not found. Check your credentials.")
Exception: Form ID not found. Check your credentials.

**Comment by algirdasc** [comment]
Užmesk akį į https://github.com/algirdasc/hass-eso/issues/2

**Comment by gramasx** [comment]
Ačiū!!
Tas pats buvo su pranešimu ESO puslapyje atnaujinti kontaktus. Patvirtinus kontaktus pradėjo veikti. Gal yra prasmė į aprašymą idėti, nes manau, čia daugeliui tas bus?
